# Generated by Django 4.2.5 on 2024-01-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(help_text='Выберите специализацию', related_name='jobs', to='users.category', verbose_name='Специализация'),
        ),
    ]
