# Generated by Django 4.2.5 on 2023-10-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('design', 'дизайн'), ('development', 'разработка'), ('testing', 'тестирование'), ('administration', 'администрирование'), ('marketing', 'маркетинг'), ('content', 'контент'), ('other', 'разное')], max_length=50, verbose_name='Название специализации')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор специализации')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ('-name',),
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ManyToManyField(help_text='Выберите специализацию', related_name='jobs', to='users.industry', verbose_name='Специализация'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
