# Generated by Django 4.2.5 on 2024-01-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofile',
            name='file',
            field=models.FileField(upload_to='portfolio/'),
        ),
    ]
