# Generated by Django 4.2.5 on 2024-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_portfoliofile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='diplomafile',
            name='file',
            field=models.FileField(upload_to='education/'),
        ),
    ]
